# Generated by Django 5.2.8 on 2026-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0002_securerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='allowed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='login_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='login_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
